# -*- coding: utf-8 -*-
"""Assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kH11qncxdj7qAJ2yJkbV1fzef9BX7Isi
"""

import matplotlib.pyplot as plt
from scipy.stats import binom

import numpy as np

#number of bulbs drawn
n=4
#probability of drawing a defective bulb
p=6/30


#k0: probability of drawing no defective bulb
k0=(1-p)*(1-p)*(1-p)*(1-p)

#k1: probability of drawing one defective bulb
k1=p*(1-p)*(1-p)*(1-p)*4

#k2: probability of drawing two defective bulbs
k2=p*p*(1-p)*(1-p)*6

#k3: probability of drawing three defective bulbs
k3=p*p*p*(1-p)*4

#k4: probability of drawing four defective bulbs
k4=p*p*p*p

Prob_k0=binom.pmf(0,n,p)
Prob_k1=binom.pmf(1,n,p)
Prob_k2=binom.pmf(2,n,p)
Prob_k3=binom.pmf(3,n,p)
Prob_k4=binom.pmf(4,n,p)


Number_of_defective_bulbs_drawn=[0,1,2,3,4]
Probability=[k0,k1,k2,k3,k4]
plt.bar(Number_of_defective_bulbs_drawn,Probability)
plt.xlabel('Number of defective bulbs drawn')
plt.ylabel('Probability')
plt.title('Probability distribution of the number of defective bulbs')
plt.show()