# -*- coding: utf-8 -*-
"""Assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kH11qncxdj7qAJ2yJkbV1fzef9BX7Isi
"""

import matplotlib.pyplot as plt
from scipy.stats import binom

#number of bulbs drawn
n=4
#probability of drawing a defective bulb
p=6/30


Prob_k0=binom.pmf(0,n,p)
Prob_k1=binom.pmf(1,n,p)
Prob_k2=binom.pmf(2,n,p)
Prob_k3=binom.pmf(3,n,p)
Prob_k4=binom.pmf(4,n,p)


Number_of_defective_bulbs_drawn=[0,1,2,3,4]
Probability=[Prob_k0,Prob_k1,Prob_k2,Prob_k3,Prob_k4]
plt.bar(Number_of_defective_bulbs_drawn,Probability)
plt.xlabel('Number of defective bulbs drawn')
plt.ylabel('Probability')
plt.title('Probability distribution of the number of defective bulbs')
plt.show()