# -*- coding: utf-8 -*-
"""Assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kH11qncxdj7qAJ2yJkbV1fzef9BX7Isi
"""

import matplotlib.pyplot as plt
Number_of_defective_bulbs_drawn=[0,1,2,3,4]
Probability=[0.41,0.41,0.15,0.025,0.0016]
plt.bar(Number_of_defective_bulbs_drawn,Probability)
plt.xlabel('Number of defective bulbs drawn')
plt.ylabel('Probability')
plt.title('Probability distribution of the number of defective bulbs')
plt.show()