# -*- coding: utf-8 -*-
"""Assignment-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umMfu-42Q9po52vCifzJttfXC2_2nPwd
"""

import matplotlib.pyplot as plt
from scipy.stats import binom
import numpy as np
import random

P=[0.4096,0.4096,0.1536,0.0256,0.0016]

#number of bulbs drawn
n=4
#probability of drawing a defective bulb
p=6/30


Prob_k0=binom.pmf(0,n,p)
Prob_k1=binom.pmf(1,n,p)
Prob_k2=binom.pmf(2,n,p)
Prob_k3=binom.pmf(3,n,p)
Prob_k4=binom.pmf(4,n,p)

p_simulated=[Prob_k0,Prob_k1,Prob_k2,Prob_k3,Prob_k4]


#plotting pdf 
x=[0,1,2,3,4]
plt.title("plot of PDF")
plt.xlabel('x')
plt.ylabel('P(X=x)')
plt.stem(x,P, markerfmt ='o', label='theoritical')
plt.stem(x, p_simulated, markerfmt ='.', label='simulation')
plt.legend()
plt.show()